template: Hello, %s!
defaultName: Stranger

#Server configuration
server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: example.keystore
      keyStorePassword: example
  adminConnectors:
    - type: http
      port: 8085
    - type: https
      port: 8444
      keyStorePath: example.keystore
      keyStorePassword: example

# Database settings
database:
    # the name of the JDBC driver
    driverClass: org.h2.Driver
    # the username
    user: sa
    # the password
    password: 
    # the JDBC URL; the database is called example
    url: jdbc:h2:./target/example

# the key needs to match the configuration key of the renderer (ViewRenderer::getConfigurationKey)
viewRendererConfiguration:
    freemarker:
        strict_syntax: yes
        whitespace_stripping: yes
        
# Logging settings      
logging:
  level: INFO
  loggers:
    com.example.helloworld: DEBUG   