template: Hello, %s!
defaultName: Stranger

# use the simple server factory if you only want to run on a single port
# HEROKU NOTE - the port gets be overridden with the Heroku $PORT in the Procfile
server:
  type: simple
  applicationContextPath: /
  #adminContextPath: /admin # If you plan to use an admin path, you'll need to also use non-root app path
  connector:
    type: http
    port: 8080
    
# HEROKU NOTE - Heroku only opens a single port so can't use the usual Dropwizard app-and-admin configuration
#Server configuration
#server:
#  applicationConnectors:
#    - type: http
#      port: 8080
#    - type: https
#      port: 8043
#      keyStorePath: example.keystore
#      keyStorePassword: example
#  adminConnectors:
#    - type: http
#      port: 8081
#    - type: https
#      port: 8044
#      keyStorePath: example.keystore
#      keyStorePassword: example

# Database settings
database:
    # the name of the JDBC driver
    driverClass: org.h2.Driver
    # the username
    user: sa
    # the password
    password: 
    # the JDBC URL; the database is called example
    url: jdbc:h2:./db/example

# the key needs to match the configuration key of the renderer (ViewRenderer::getConfigurationKey)
viewRendererConfiguration:
    freemarker:
        strict_syntax: yes
        whitespace_stripping: yes
        
# Logging settings      
logging:
  level: INFO
  loggers:
    com.example.helloworld: DEBUG   